spring.application.name=inmobiliaria-app

# ── BASE DE DATOS PRODUCCIÓN (AWS RDS) ──────────────────────
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / HIBERNATE ─────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# ── THYMELEAF ────────────────────────────────────────────────
spring.thymeleaf.cache=true

# ── SERVIDOR ─────────────────────────────────────────────────
server.address=0.0.0.0
server.port=8080

# ── UPLOADS ──────────────────────────────────────────────────
app.upload.dir=uploads/property-media
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.enabled=true

# ── SESIÓN ───────────────────────────────────────────────────
server.servlet.session.persistent=false
server.servlet.session.timeout=8h

# ── Cloudinary ───────────────────────────────────────────────
cloudinary.cloud-name=di0yccxft
cloudinary.api-key=725987519795384
cloudinary.api-secret=U5Bl5uGcKO_AOgXpPeRsTULLKgg

# ── Contacto ─────────────────────────────────────────────────
contact.mail.to=g.correa.bastos@gmail.com

# ── JavaMailSender ───────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=g.correa.bastos@gmail.com
spring.mail.password=ndzw djgv bbui jyxg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ── Contacto público ─────────────────────────────────────────
app.contact.email=g.correa.bastos@gmail.com
app.contact.phone=+34 618 097 990